# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Manikandan, world!
- task: AzurePowerShell@4
  inputs:
    ScriptType: 'InlineScript'
    Inline: 'Add-AzureRmAccount -Subscription "AZU-P00-RA01-NP" 

$resourceGroup = "AZ19D1-ZeroTouch"
$location = "West US 2"
$vmName = "Testing-Mani"

# Create user object
$User = "User01"
$PWord = ConvertTo-SecureString -String "P@sSwOrd" -AsPlainText -Force
$cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
#$cred = Get-Credential -Message "Enter a username and password for the virtual machine." -credential User01

# Create a resource group
#New-AzureRmResourceGroup -Name $resourceGroup -Location $location

# Create a virtual machine
New-AzureRmVM `
  -ResourceGroupName $resourceGroup `
  -Name $vmName `
  -Location $location `
  -ImageName "Win2016Datacenter" `
  -VirtualNetworkName "myVnet" `
  -SubnetName "mySubnet" `
  -SecurityGroupName "myNetworkSecurityGroup" `
  -PublicIpAddressName "myPublicIp" `
  -Credential $cred `
  -OpenPorts 3389
  
# You can also pass predefined and custom variables to this script using arguments'
    TargetAzurePs: 'LatestVersion'
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
